### ISSUE TITLE
ERROR: AttributeError: 'NoneType' object has no attribute 'cancel' (self._heartbeatTask)

### ISSUE THREAD

**Issue by ant0n-0x0000** [0y9/Fake-Verify-Bot-Discord#13]
When I run the bot, I get an error that self._heartbeatTask has no type,  meaning that somewhere on line 189, there's an issue. I'm not a python developer, so I'm not exactly sure what to do; other than that, everything works; no QR code is displayed in the message.

![image](https://user-images.githubusercontent.com/22851444/197317362-e5fce33a-fd16-4b0d-a739-a963c58790cf.png)
![image](https://user-images.githubusercontent.com/22851444/197317395-cf8fc460-dd6a-4724-8d9f-d2c374555c4c.png)

**Comment by ant0n-0x0000** [comment]
### Solution:
1. Delete all lines from 129 to 227,
2. Open your terminal/command prompt and run `pip install remoteauthclient`,
3. Go back to the main.py file & at the top of the file, add a new 2nd line that says: `from remoteauthclient import RemoteAuthClient`

**Comment by Zoltak-Dev** [comment]
niiice thx man
